Chap/RazorPages/Solved/ItemRazorV7/Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace ItemRazorV7.Models
{
    public class Item
    {
        [Display(Name = "Item ID")]
        [Required(ErrorMessage = "Der skal angives et ID til Item")]
		[Range(typeof(int), "0", "10000", ErrorMessage = "ID skal være mellem {1} og {2}")]
		public int? Id { get; set; }

        [Display(Name = "Item Navn")]
        [Required(ErrorMessage = "Item skal have et navn")]
        public string? Name { get; set; }

        [Display(Name = "Pris")]
        [Required(ErrorMessage = "Der skal angives en pris")]
        public double? Price { get; set; }

        public Item()
        {
        }

        public Item(int id, string name, double price)
        {
            Id = id;
            Name = name;
            Price = price;
        }
    }
}

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/CreateItem.cshtml.cs
using ItemRazorV7.Models;
using ItemRazorV7.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
#nullable disable

namespace ItemRazorV7.Pages.Items
{
    public class CreateItemModel : PageModel
    {
        private IItemService _itemService;

        public CreateItemModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        [BindProperty]
        public Item Item { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _itemService.AddItem(Item);
            return RedirectToPage("GetAllItems");
        }
    }
}

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/DeleteItem.cshtml.cs
using ItemRazorV7.Models;
using ItemRazorV7.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
#nullable disable

namespace ItemRazorV7.Pages.Items
{
    public class DeleteItemModel : PageModel
    {
        private IItemService _itemService;

        public DeleteItemModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        [BindProperty]
        public Item Item { get; set; }


        public IActionResult OnGet(int id)
        {
            Item = _itemService.GetItem(id);
            if (Item == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost()
        {
            Item deletedItem = _itemService.DeleteItem(Item.Id);
            if (deletedItem == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return RedirectToPage("GetAllItems");
        }
    }
}

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/EditItem.cshtml.cs
using ItemRazorV7.Models;
using ItemRazorV7.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
#nullable disable

namespace ItemRazorV7.Pages.Items
{
    public class EditItemModel : PageModel
    {
        private IItemService _itemService;

        public EditItemModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        [BindProperty]
        public Item Item { get; set; }

        public IActionResult OnGet(int id)
        {
            Item = _itemService.GetItem(id);
            if (Item == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _itemService.UpdateItem(Item);
            return RedirectToPage("GetAllItems");
        }
    }
}

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/GetAllItems.cshtml.cs
using ItemRazorV7.Models;
using ItemRazorV7.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ItemRazorV7.Pages.Items
{
    public class GetAllItemsModel : PageModel
    {
        private IItemService _itemService;

        public GetAllItemsModel(IItemService itemService)
        {
            _itemService = itemService;
			SearchString = string.Empty;
		}

        public List<Item>? Items { get; private set; }

        [BindProperty] 
        public string SearchString { get; set; }

        [BindProperty]
        public int MinPrice { get; set; }

        [BindProperty]
        public int MaxPrice { get; set; }


        public void OnGet()
        {
            Items = _itemService.GetItems();
        }

        public IActionResult OnPostNameSearch()
        {
            Items = _itemService.NameSearch(SearchString).ToList();
            return Page();
        }

        public IActionResult OnPostPriceFilter()
        {
            Items = _itemService.PriceFilter(MaxPrice, MinPrice).ToList();
            return Page();
        }
    }
}

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/CreateItem.cshtml
@page
@model ItemRazorV7.Pages.Items.CreateItemModel
@{
}

 <form method="post">
	 <div class="form-group">
		 <label asp-for="Item.Id" class="control-label"></label>
		 <input asp-for="Item.Id" class="form-control"/>
		 <span asp-validation-for="Item.Id" class="text-danger"></span>
	 </div>
	<div class="form-group">
		<label asp-for="Item.Name" class="control-label"></label>
		<input asp-for="Item.Name" class="form-control" />
		<span asp-validation-for="@Model.Item.Name" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Item.Price" class="control-label"></label>
		<input asp-for="Item.Price" class="form-control" />
		<span asp-validation-for="Item.Price" class="text-danger"></span>
	</div>

	<p>
		<div class="form-group">
			<input type="submit" value="Create" class="btn btn-primary" />
		</div>
	</p>
</form>

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/DeleteItem.cshtml
@page
@model ItemRazorV7.Pages.Items.DeleteItemModel
@{
}

<h1>Delete Confirmation></h1>
<div class="alert alert-danger">
	<h5>Are you sure you want to delete Item - @Model.Item.Name</h5>
	<form method="post">
		<button type="submit" class="btn btn-danger">Yes</button>
		<a class="btn btn-primary" asp-page="/Items/GetAllItems">No</a>
	</form>
</div>

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/EditItem.cshtml
@page "{id:int}"
@model ItemRazorV7.Pages.Items.EditItemModel
@{
}

<form method="post">
	<div class="form-group">
		<label asp-for="Item.Id" class="control-lable"></label>
		<input asp-for="Item.Id" class="form-control" readonly="@(true)"/>
	</div>
	<div class="form-group">
		<label asp-for="Item.Name" class="control-lable"></label>
		<input asp-for="Item.Name" class="form-control" />
		<span asp-validation-for="Item.Name" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Item.Price" class="control-lable"></label>
		<input asp-for="Item.Price" class="form-control" />
		<span asp-validation-for="Item.Price" class="text-danger"></span>
	</div>

	<p>
		<div class="form-group">
			<input type="submit" value="Update" class="btn btn-primary" />
		</div>
	</p>
</form>

<p>
	<a asp-page="/Items/GetAllItems">Back to List</a>
</p>

Chap/RazorPages/Solved/ItemRazorV7/Pages/Items/GetAllItems.cshtml
@page
@model ItemRazorV7.Pages.Items.GetAllItemsModel
@{
}

<h1>Items</h1>

<div class="row">
	<div class="col-4"><h5>Search Name</h5></div>
	<div class="col-4"><h5>Filter Price</h5></div>
	<div class="col-4"></div>
</div>

<div class="row">
	<div class="col-4">
		<form method="post" class="form-inline">
			<div class="input-group mb-3">
				<input asp-for="SearchString" class="form-control mr-1" placeholder="Enter search term" />
				<input type="submit" asp-page-handler="NameSearch" value="Search" class="btn btn-primary" />
			</div>
		</form>
	</div>

	<div class="col-5">
		<form method="post" class="form-inline">
			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Min</span>
				</div>
				<input asp-for="MinPrice" class="form-control mr-1"/>
				<div class="input-group-prepend">
					<span class="input-group-text">Max</span>
				</div>
				<input asp-for="MaxPrice" class="form-control mr-1"/>
				<input type="submit" asp-page-handler="PriceFilter" value="Filter" class="btn btn-primary" />
			</div>
		</form>
	</div>

	<div class="col-2"></div>
</div>

<table class="table table-bordered table-hover table-striped table-opacity" width="60%">
	<colgroup>
		<col style="width : 5%">
		<col style="width : 77%">
		<col style="width : 9%">
		<col style="width : 9%">
	</colgroup>
	<thead>
		<tr class="btn-secondary active">
			<th>
				Id
			</th>
			<th>
				Name
			</th>
			<th>
				Price
			</th>
			<th>
				Actions
			</th>
		</tr>
	</thead>
	<tbody>
		@if (Model.Items != null)
		{
			foreach (var item in Model.Items)
			{
				<tr class="btn-secondary">
					<td>
						@item.Id
					</td>
					<td>
						@item.Name
					</td>
					<td>
						@item.Price
					</td>
					<td>
						<a class="btn btn-primary btn-sm" type="button" title="Edit" asp-page="EditItem" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
						<a class="btn btn-danger btn-sm " type="button" title="Delete" asp-page="DeleteItem" asp-route-id="@item.Id"><i class="fa fa-trash"></i></a>
					</td>
				</tr>
			}
		}
	</tbody>
</table>

<p>
	<a class="btn btn-primary" asp-page="CreateItem"> Create a new Item </a>
</p>